# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Chatterjee's Xi Coefficient
#' 
#' @param x Numeric vector
#' @param y Numeric vector
#' @return Double value of Xi
#' @export
xi_coefficient <- function(x, y) {
    .Call('_xiacf_xi_coefficient', PACKAGE = 'xiacf', x, y)
}

generate_iaaft_surrogates <- function(x, n_surr, max_iter = 100L) {
    .Call('_xiacf_generate_iaaft_surrogates', PACKAGE = 'xiacf', x, n_surr, max_iter)
}

#' Compute Xi Statistics for Lags (Core Engine)
#' 
#' Calculates Chatterjee's Xi for multiple lags and generates IAAFT surrogates.
#' 
#' @param x Numeric vector (time series).
#' @param max_lag Maximum lag to compute.
#' @param n_surr Number of surrogate datasets to generate.
#' @return A list containing `xi_original` and `xi_surrogates`.
#' @export
compute_xi_lags <- function(x, max_lag, n_surr) {
    .Call('_xiacf_compute_xi_lags', PACKAGE = 'xiacf', x, max_lag, n_surr)
}

